In [18]:
from training_utilities_2nd_part import *
from training_utilities import *

In [19]:
twitter_df = pd.read_csv("/Users/forough/PycharmProjects/mitigation3/Aiops_data_splitting_paper/code/Multivariate_time_series/twitter2/twitter3.csv")

twitter_df = twitter_df[4: len(twitter_df)-120]

twitter_df['Date'] = pd.to_datetime(twitter_df['Date'])
twitter_df['YearMonth'] = twitter_df['Date'].dt.to_period('M')
one_hot = pd.get_dummies(twitter_df['Symbol'], prefix='Symbol')
twitter_df = pd.concat([twitter_df, one_hot], axis=1)
twitter_df = twitter_df.drop(columns = ['Series', 'Trades', 'Symbol'])
twitter_df

,Date,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Deliverable Volume,%Deliverble,YearMonth,Symbol_ADANIPORTS,Symbol_MUNDRAPORT
0,2007-11-27,440.00,770.00,1050.00,770.00,959.0,962.90,984.72,27294366,2.687719e+15,9859619,0.3612,2007-11,False,True
1,2007-11-28,962.90,984.00,990.00,874.00,885.0,893.90,941.38,4581338,4.312765e+14,1453278,0.3172,2007-11,False,True
2,2007-11-29,893.90,909.00,914.75,841.00,887.0,884.20,888.09,5124121,4.550658e+14,1069678,0.2088,2007-11,False,True
3,2007-11-30,884.20,890.00,958.00,890.00,929.0,921.55,929.17,4609762,4.283257e+14,1260913,0.2735,2007-11,False,True
4,2007-12-03,921.55,939.75,995.00,922.00,980.0,969.30,965.65,2977470,2.875200e+14,816123,0.2741,2007-12,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3317,2021-04-26,725.35,733.00,739.65,728.90,729.2,730.75,733.25,9390549,6.885658e+14,838079,0.0892,2021-04,True,False
3318,2021-04-27,730.75,735.00,757.50,727.35,748.6,749.15,747.67,20573107,1.538191e+15,1779639,0.0865,2021-04,True,False
3319,2021-04-28,749.15,755.00,760.00,741.10,743.4,746.25,751.02,11156977,8.379106e+14,1342353,0.1203,2021-04,True,False
3320,2021-04-29,746.25,753.20,765.85,743.40,746.4,746.75,753.06,13851910,1.043139e+15,1304895,0.0942,2021-04,True,False
3321,2021-04-30,746.75,739.00,759.45,724.50,726.4,730.05,743.35,12600934,9.366911e+14,3514692,0.2789,2021-04,True,False

In [20]:
# twitter
# from variables_to_specify_twitter import *
columns_to_normalize = ['Prev Close', 'Open', 'High', 'Low', 'Last','Close', 'VWAP', 'Volume', 'Turnover', 'Deliverable Volume','%Deliverble']
twitter_target_col = 'Close'
forecast_avg_target_col_name = 'forecast_avg_Close'
avg_target_col_name = 'avg_Close'
No_of_datapoints_in_one_day = 1
date_col_name = 'Date'
one_month_window_size = 31
one_month_days =31
out_columns = ['Training dataset', 'Testing dataset', 'mae', 'mse', 'rmse', 'r2', 'mape', 'training_time',
              'Testing Error', 'testing_time']

twitter_drop_columnss = [twitter_target_col]+['YearMonth']+[date_col_name]
twitter_windows = [50,150,310,450,600,750,900]

print(twitter_target_col)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
twitter_df[columns_to_normalize] = scaler.fit_transform(twitter_df[columns_to_normalize])
twitter_df = twitter_df.dropna().reset_index(drop=True)

twitter_time_steps = 1

daily_df_avg = twitter_df[['Close']].copy()
daily_df_avg.rename(columns={'Close': 'avg_Close'}, inplace=True)

Close

,Date,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Deliverable Volume,%Deliverble,YearMonth,Symbol_ADANIPORTS,Symbol_MUNDRAPORT
0,2007-11-27,0.276794,0.550634,0.774216,0.570576,0.709167,0.712743,0.734103,0.279227,0.329318,0.439703,0.322305,2007-11,False,True
1,2007-11-28,0.712743,0.728634,0.724774,0.659896,0.647500,0.655217,0.697799,0.046763,0.052818,0.064606,0.274102,2007-11,False,True
2,2007-11-29,0.655217,0.666251,0.662766,0.631554,0.649167,0.647130,0.653161,0.052318,0.055733,0.047490,0.155346,2007-11,False,True
3,2007-11-30,0.647130,0.650447,0.698406,0.673638,0.684167,0.678269,0.687572,0.047054,0.052456,0.056023,0.226227,2007-11,False,True
4,2007-12-03,0.678269,0.691828,0.728895,0.701121,0.726667,0.718079,0.718129,0.030347,0.035202,0.036176,0.226884,2007-12,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3317,2021-04-26,0.514694,0.519859,0.518479,0.535277,0.517667,0.519196,0.523459,0.095984,0.084346,0.037155,0.024321,2021-04,True,False
3318,2021-04-27,0.519196,0.521522,0.533188,0.533946,0.533833,0.534537,0.535537,0.210436,0.188457,0.079169,0.021363,2021-04,True,False
3319,2021-04-28,0.534537,0.538158,0.535248,0.545755,0.529500,0.532119,0.538344,0.114063,0.102646,0.059657,0.058392,2021-04,True,False
3320,2021-04-29,0.532119,0.536660,0.540068,0.547730,0.532000,0.532536,0.540052,0.141645,0.127794,0.057985,0.029798,2021-04,True,False
3321,2021-04-30,0.532536,0.524849,0.534795,0.531498,0.515333,0.518613,0.531919,0.128842,0.114750,0.156588,0.232143,2021-04,True,False

# stationary

In [21]:
twitter_len_of_training_data_of_stationary_model =258

train = twitter_df[0:twitter_len_of_training_data_of_stationary_model] 
test = twitter_df[twitter_len_of_training_data_of_stationary_model:]

eval_df_first_month, stationary_model1 = twitter_stationary_model_with_hptuning(train, test, 1, out_columns, twitter_target_col, twitter_drop_columnss)
sum_training_time_stat1 = eval_df_first_month['training_time'].sum()
print('sum_training_time is: ', sum_training_time_stat1)
print(eval_df_first_month['Testing Error'].mean())
print("mae is : ", eval_df_first_month['mae'].mean())

Model Type: RandomForestRegressor
Storage Required: 2.25 MB
model storage is:  2.245224952697754


total_time is:  0.1801577090000137
sum_training_time is:  0.1445272500000101
0.0030819595603613394
mae is :  0.033461880837028515

# Model reuse

In [22]:
seasonality_periods_acf_ls, seasonality_periods_acf, segmented_daily_df_avg, filtered_most_similar_dict_wass, filtered_most_similar_dict_tvd, forecast_daily_df_avg, segmented_forecast_daily_df_avg, filtered_forecasted_most_similar_dict_wass, filtered_forecasted_most_similar_dict_tvd = get_seasonality_segments_and_similarities(daily_df_avg, avg_target_col_name, forecast_avg_target_col_name, 258)
seasonality_periods_acf = seasonality_periods_acf_ls[0]

Detected seasonality periods (ACF): [258 262 327 330 355 394 421 469 473 479 491]
median_value is:  394

# drift detection

In [23]:
df_copy = twitter_df[[twitter_target_col]]
target_col = twitter_target_col
time_steps = twitter_time_steps

df_copy['date'] = pd.to_datetime(df_copy.index)
multiplier = twitter_time_steps
x = 258* multiplier
window_len_=[x]
drift_results_df_ls = []
for i in window_len_:
    start_drift_detection_time = timeit.default_timer()
    drift_results_df = detect_drift_univariate(
        df_copy,
        target_col=twitter_target_col,
        window_lengths=window_len_,
        arima_order=(1, 0, 0)
    )
    drift_results_df_ls.append(drift_results_df)
    drift_detection_time = timeit.default_timer() - start_drift_detection_time
    num_true = drift_results_df['drift_detected'].sum()
    print("i is: ", i, " and the Number of True values in 'drift_detected':", num_true, " total number of rows are : ", len(drift_results_df))
    print("drift detection time is: ", drift_detection_time)
    drift_results_df = drift_results_df_ls[0]
    drift_indices = list(drift_results_df.index[drift_results_df['drift_detected']])
    print("indices are: ", drift_indices)

Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
i is:  258  and the Number of True values in 'drift_detected': 4  total number of rows are :  11
drift detection time is:  1.8963434170000255
indices are:  [0, 5, 8, 10]

In [24]:
eval_df_monthly2, avg_ml_storage1 = new_copied_reuse_with_hptuning_no_while_loop_with_drift(filtered_most_similar_dict_wass, stationary_model1, twitter_len_of_training_data_of_stationary_model,twitter_df, "SA", twitter_target_col, twitter_drop_columnss, twitter_time_steps, seasonality_periods_acf, No_of_datapoints_in_one_day, drift_indices, 1)

window is:  258
i/window is :  1.0
Model Type: RandomForestRegressor
Storage Required: 2.25 MB


window is:  516
i/window is :  2.0
similar_month_index is :  0
month_index:  2




window is:  774
i/window is :  3.0
similar_month_index is :  1
month_index:  3




window is:  1032
i/window is :  4.0
Model Type: RandomForestRegressor
Storage Required: 2.09 MB


window is:  1290
i/window is :  5.0
similar_month_index is :  3
previous_model_i is :  1290
math.floor(previous_model_i/window) is:  5
len(models_ls) is: 4
Model Type: RandomForestRegressor
Storage Required: 2.07 MB


window is:  1548
i/window is :  6.0
Model Type: RandomForestRegressor
Storage Required: 2.07 MB


window is:  1806
i/window is :  7.0
Model Type: RandomForestRegressor
Storage Required: 2.21 MB


window is:  2064
i/window is :  8.0
similar_month_index is :  6
month_index:  8




window is:  2322
i/window is :  9.0
similar_month_index is :  7
month_index:  9




window is:  2580
i/window is :  10.0
Model Type: RandomForestRegressor
Storage Required: 2.18 MB


window is:  2838
i/window is :  11.0
Model Type: RandomForestRegressor
Storage Required: 2.19 MB


window is:  3096


total_reuse_time is :  1.2178033339996546
reuse_trained_and_stored_models_count is :  7
avg_ml_storage:  2.1496242795671736






mean_stationary_model_testing_error_of_months_in_similar_dict is:  0.0033263552739923054
mean_periodical_testing_error_of_months_in_similar_dict is:  0.0015177621888603611
mean_reused_model_testing_error_of_months_in_similar_dict is:  0.0020675906132968987
mean_drift_model_testing_error_of_months_in_similar_dict is:  0.002637460102764918


MAE results are:
mae_mean_stationary_model_testing_error_mae_of_months_in_similar_dict is:  0.03591801134129156
mae_mean_periodical_testing_error_mae_of_months_in_similar_dict is:  0.017975586561270684
mae_mean_reused_model_testing_error_mae_of_months_in_similar_dict is:  0.023772256023733677
mae_mean_drift_model_testing_error_mae_of_months_in_similar_dict is:  0.0306088139234358
Average mse in random model is:  0.03083978697164583
average mae in random model is:  0.10949273611576991

In [25]:
eval_df_monthly2, avg_ml_storage2 = new_copied_reuse_with_hptuning_no_while_loop_with_drift(filtered_most_similar_dict_tvd, stationary_model1, twitter_len_of_training_data_of_stationary_model,twitter_df, "SA", twitter_target_col, twitter_drop_columnss, twitter_time_steps, seasonality_periods_acf, No_of_datapoints_in_one_day, drift_indices, 1)

window is:  258
i/window is :  1.0
Model Type: RandomForestRegressor
Storage Required: 2.25 MB


window is:  516
i/window is :  2.0
similar_month_index is :  0
month_index:  2




window is:  774
i/window is :  3.0
similar_month_index is :  1
month_index:  3




window is:  1032
i/window is :  4.0
similar_month_index is :  0
month_index:  4




window is:  1290
i/window is :  5.0
similar_month_index is :  1
month_index:  5




window is:  1548
i/window is :  6.0
similar_month_index is :  1
month_index:  6




window is:  1806
i/window is :  7.0
similar_month_index is :  0
month_index:  7




window is:  2064
i/window is :  8.0
similar_month_index is :  6
previous_model_i is :  2064
math.floor(previous_model_i/window) is:  8
len(models_ls) is: 7
Model Type: RandomForestRegressor
Storage Required: 2.18 MB


window is:  2322
i/window is :  9.0
Model Type: RandomForestRegressor
Storage Required: 2.18 MB


window is:  2580
i/window is :  10.0
Model Type: RandomForestRegressor
Storage Required: 2.18 MB


window is:  2838
i/window is :  11.0
similar_month_index is :  7
previous_model_i is :  2838
math.floor(previous_model_i/window) is:  11
len(models_ls) is: 10
Model Type: RandomForestRegressor
Storage Required: 2.16 MB


window is:  3096


total_reuse_time is :  0.9471200839993799
reuse_trained_and_stored_models_count is :  5
avg_ml_storage:  2.1905954360961912






mean_stationary_model_testing_error_of_months_in_similar_dict is:  0.0033263552739923054
mean_periodical_testing_error_of_months_in_similar_dict is:  0.0015177621888603611
mean_reused_model_testing_error_of_months_in_similar_dict is:  0.0033735074424546675
mean_drift_model_testing_error_of_months_in_similar_dict is:  0.006257745528907797


MAE results are:
mae_mean_stationary_model_testing_error_mae_of_months_in_similar_dict is:  0.03591801134129156
mae_mean_periodical_testing_error_mae_of_months_in_similar_dict is:  0.017975586561270684
mae_mean_reused_model_testing_error_mae_of_months_in_similar_dict is:  0.036540271232489645
mae_mean_drift_model_testing_error_mae_of_months_in_similar_dict is:  0.057840115511599136
Average mse in random model is:  0.03083978697164583
average mae in random model is:  0.10949273611576991

In [26]:
eval_df_monthly2, avg_ml_storage3 = new_copied_reuse_with_hptuning_no_while_loop_with_drift(filtered_forecasted_most_similar_dict_wass, stationary_model1, twitter_len_of_training_data_of_stationary_model,twitter_df, "ES", twitter_target_col, twitter_drop_columnss, twitter_time_steps, seasonality_periods_acf, No_of_datapoints_in_one_day, drift_indices, 1)

window is:  258
Model Type: RandomForestRegressor
Storage Required: 2.25 MB


window is:  516
Model Type: RandomForestRegressor
Storage Required: 2.22 MB


window is:  774
similar_month_index is :  0
month_index:  2



window is:  1032
similar_month_index is :  1
month_index:  3




window is:  1290
Model Type: RandomForestRegressor
Storage Required: 2.09 MB


window is:  1548
similar_month_index is :  3
previous_model_i is :  1548
math.floor(previous_model_i/window) is:  6
len(models_ls) is: 5
Model Type: RandomForestRegressor
Storage Required: 2.21 MB


window is:  1806
Model Type: RandomForestRegressor
Storage Required: 2.21 MB


window is:  2064
similar_month_index is :  1
month_index:  7




window is:  2322
similar_month_index is :  1
month_index:  8




window is:  2580
similar_month_index is :  7
previous_model_i is :  2580
math.floor(previous_model_i/window) is:  10
len(models_ls) is: 9
Model Type: RandomForestRegressor
Storage Required: 2.19 MB


window is:  2838
Model Type: RandomForestRegressor
Storage Required: 2.19 MB


window is:  3096


total_reuse_time is :  1.2713251249999757
reuse_trained_and_stored_models_count is :  7
avg_ml_storage:  2.194079671587263






mean_stationary_model_testing_error_of_months_in_similar_dict is:  0.0033263552739923054
mean_periodical_testing_error_of_months_in_similar_dict is:  0.0015177621888603611
mean_reused_model_testing_error_of_months_in_similar_dict is:  0.003606236997063778
mean_drift_model_testing_error_of_months_in_similar_dict is:  0.006662313805128214


MAE results are:
mae_mean_stationary_model_testing_error_mae_of_months_in_similar_dict is:  0.03591801134129156
mae_mean_periodical_testing_error_mae_of_months_in_similar_dict is:  0.017975586561270684
mae_mean_reused_model_testing_error_mae_of_months_in_similar_dict is:  0.03278507641113756
mae_mean_drift_model_testing_error_mae_of_months_in_similar_dict is:  0.0694451125478161
Average mse in random model is:  0.03083978697164583
average mae in random model is:  0.10949273611576991

In [27]:
eval_df_monthly2, avg_ml_storage4 = new_copied_reuse_with_hptuning_no_while_loop_with_drift(filtered_forecasted_most_similar_dict_tvd, stationary_model1, twitter_len_of_training_data_of_stationary_model,twitter_df, "ES", twitter_target_col, twitter_drop_columnss, twitter_time_steps, seasonality_periods_acf, No_of_datapoints_in_one_day, drift_indices, 1)

window is:  258
Model Type: RandomForestRegressor
Storage Required: 2.25 MB


window is:  516
Model Type: RandomForestRegressor
Storage Required: 2.22 MB


window is:  774
Model Type: RandomForestRegressor
Storage Required: 2.20 MB


window is:  1032
Model Type: RandomForestRegressor
Storage Required: 2.09 MB


window is:  1290
similar_month_index is :  2
month_index:  4




window is:  1548
similar_month_index is :  1
month_index:  5




window is:  1806
Model Type: RandomForestRegressor
Storage Required: 2.21 MB


window is:  2064
similar_month_index is :  4
previous_model_i is :  2064
math.floor(previous_model_i/window) is:  8
len(models_ls) is: 7
Model Type: RandomForestRegressor
Storage Required: 2.18 MB


window is:  2322
similar_month_index is :  2
month_index:  8




window is:  2580
similar_month_index is :  4
previous_model_i is :  2580
math.floor(previous_model_i/window) is:  10
len(models_ls) is: 9
Model Type: RandomForestRegressor
Storage Required: 2.19 MB


window is:  2838
similar_month_index is :  8
previous_model_i is :  2838
math.floor(previous_model_i/window) is:  11
len(models_ls) is: 10
Model Type: RandomForestRegressor
Storage Required: 2.16 MB


window is:  3096


total_reuse_time is :  1.922597375000123
reuse_trained_and_stored_models_count is :  8
avg_ml_storage:  2.18759822845459






mean_stationary_model_testing_error_of_months_in_similar_dict is:  0.0033263552739923054
mean_periodical_testing_error_of_months_in_similar_dict is:  0.0015177621888603611
mean_reused_model_testing_error_of_months_in_similar_dict is:  0.0024495129358016875
mean_drift_model_testing_error_of_months_in_similar_dict is:  0.0045030336301872574


MAE results are:
mae_mean_stationary_model_testing_error_mae_of_months_in_similar_dict is:  0.03591801134129156
mae_mean_periodical_testing_error_mae_of_months_in_similar_dict is:  0.017975586561270684
mae_mean_reused_model_testing_error_mae_of_months_in_similar_dict is:  0.021944481190007473
mae_mean_drift_model_testing_error_mae_of_months_in_similar_dict is:  0.05142505237381086
Average mse in random model is:  0.03083978697164583
average mae in random model is:  0.10949273611576991

In [28]:
avg_ml_storage_reuse = (avg_ml_storage1+avg_ml_storage2+avg_ml_storage3+avg_ml_storage4)/4
print(avg_ml_storage_reuse)

2.180474403926304

# informed

In [29]:
informed_update(stationary_model1,twitter_df, target_col, twitter_drop_columnss,time_steps, seasonality_periods_acf,No_of_datapoints_in_one_day, drift_indices, 1)

window is:  258
Model Type: RandomForestRegressor
Storage Required: 2.25 MB
window is:  516
window is:  774
window is:  1032
window is:  1290
Model Type: RandomForestRegressor
Storage Required: 2.09 MB
window is:  1548
window is:  1806
window is:  2064
Model Type: RandomForestRegressor
Storage Required: 2.18 MB
window is:  2322
window is:  2580
Model Type: RandomForestRegressor
Storage Required: 2.18 MB
window is:  2838
window is:  3096
Informed total_time:  0.7091758750000281
avg_ml_storage:  2.172818183898926

# periodical

In [30]:
periodical_retraining_with_hptuning(1, twitter_df, twitter_windows, out_columns, twitter_target_col, twitter_drop_columnss)

window is : 50
window size is :  50
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.45 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.44 MB
Model Type: RandomForestRegressor
Storage Required: 0.45 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.45 MB
Model Type: RandomForestRegressor
Storage Required: 0.45 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.45 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.45 MB
Model Type: RandomForestRegressor
Storage Required: 0.43 MB
Model Type: RandomForestRegressor
Storage Required: 0.45 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.45 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.44 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.45 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.45 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.45 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.44 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.46 MB
Model Type: RandomForestRegressor
Storage Required: 0.45 MB
Model Type: RandomForestRegressor
Storage Required: 0.45 MB
Model Type: RandomForestRegressor
Storage Required: 0.47 MB
window is : 150
window size is :  150
Model Type: RandomForestRegressor
Storage Required: 1.33 MB
Model Type: RandomForestRegressor
Storage Required: 1.32 MB
Model Type: RandomForestRegressor
Storage Required: 1.30 MB
Model Type: RandomForestRegressor
Storage Required: 1.31 MB
Model Type: RandomForestRegressor
Storage Required: 1.31 MB
Model Type: RandomForestRegressor
Storage Required: 1.25 MB
Model Type: RandomForestRegressor
Storage Required: 1.29 MB
Model Type: RandomForestRegressor
Storage Required: 1.25 MB
Model Type: RandomForestRegressor
Storage Required: 1.27 MB
Model Type: RandomForestRegressor
Storage Required: 1.24 MB
Model Type: RandomForestRegressor
Storage Required: 1.30 MB
Model Type: RandomForestRegressor
Storage Required: 1.30 MB
Model Type: RandomForestRegressor
Storage Required: 1.27 MB
Model Type: RandomForestRegressor
Storage Required: 1.31 MB
Model Type: RandomForestRegressor
Storage Required: 1.29 MB
Model Type: RandomForestRegressor
Storage Required: 1.31 MB
Model Type: RandomForestRegressor
Storage Required: 1.29 MB
Model Type: RandomForestRegressor
Storage Required: 1.31 MB
Model Type: RandomForestRegressor
Storage Required: 1.29 MB
Model Type: RandomForestRegressor
Storage Required: 1.28 MB
Model Type: RandomForestRegressor
Storage Required: 1.28 MB
window is : 310
window size is :  310
Model Type: RandomForestRegressor
Storage Required: 2.69 MB
Model Type: RandomForestRegressor
Storage Required: 2.65 MB
Model Type: RandomForestRegressor
Storage Required: 2.51 MB
Model Type: RandomForestRegressor
Storage Required: 2.53 MB
Model Type: RandomForestRegressor
Storage Required: 2.50 MB
Model Type: RandomForestRegressor
Storage Required: 2.65 MB
Model Type: RandomForestRegressor
Storage Required: 2.62 MB
Model Type: RandomForestRegressor
Storage Required: 2.61 MB
Model Type: RandomForestRegressor
Storage Required: 2.65 MB
window is : 450
window size is :  450
Model Type: RandomForestRegressor
Storage Required: 3.84 MB
Model Type: RandomForestRegressor
Storage Required: 3.74 MB
Model Type: RandomForestRegressor
Storage Required: 3.62 MB
Model Type: RandomForestRegressor
Storage Required: 3.73 MB
Model Type: RandomForestRegressor
Storage Required: 3.76 MB
Model Type: RandomForestRegressor
Storage Required: 3.80 MB
window is : 600
window size is :  600
Model Type: RandomForestRegressor
Storage Required: 5.12 MB
Model Type: RandomForestRegressor
Storage Required: 4.88 MB
Model Type: RandomForestRegressor
Storage Required: 4.93 MB
Model Type: RandomForestRegressor
Storage Required: 5.03 MB
window is : 750
window size is :  750
Model Type: RandomForestRegressor
Storage Required: 6.38 MB
Model Type: RandomForestRegressor
Storage Required: 5.94 MB
Model Type: RandomForestRegressor
Storage Required: 6.23 MB
window is : 900
window size is :  900
Model Type: RandomForestRegressor
Storage Required: 7.58 MB
Model Type: RandomForestRegressor
Storage Required: 7.29 MB
average model storage : 1.4199797023426404
optimal MSE seg len time is: 1.0488069580001138
mean_ls is:  [0.0017858811695815344, 0.003042119055469399, 0.0033336702989006247, 0.0015694063922426754, 0.0029745045100663626, 0.0029432501766454406, 0.0004172367907795948]
np.min(mean_ls) is :  0.0004172367907795948
optimal_segment_number is : 900




mean_ls_mae is:  [0.017634438348345556, 0.022515074832578662, 0.02694153383622212, 0.018706397067791845, 0.030884924166631904, 0.03328348326316224, 0.011420539274945463]
np.min(mean_ls_mae) is :  0.011420539274945463
optimal_segment_number_mae is : 900
optimal MAE seg len time is: 1.0488069580001138


total_time is:  16.30643258300006

([         Training dataset     Testing dataset       mae       mse      rmse  \
  0   trained on window i-1  tested on window i  0.125196  0.019767  0.140597
  1   trained on window i-1  tested on window i  0.022102  0.001302  0.036087
  2   trained on window i-1  tested on window i  0.018377  0.000422  0.020540
  3   trained on window i-1  tested on window i  0.081777  0.009034  0.095047
  4   trained on window i-1  tested on window i  0.012416  0.000196  0.014016
  ..                    ...                 ...       ...       ...       ...
  60  trained on window i-1  tested on window i  0.010002  0.000154  0.012419
  61  trained on window i-1  tested on window i  0.003765  0.000025  0.005009
  62  trained on window i-1  tested on window i  0.001677  0.000005  0.002248
  63  trained on window i-1  tested on window i  0.060551  0.005553  0.074518
  64  trained on window i-1  tested on window i  0.101285  0.014811  0.121700

            r2       mape  training_time  Testing Error  testing_time
  0  -3.092662  31.378551       0.070682       0.019767      0.003603
  1   0.883025   4.125702       0.067314       0.001302      0.003304
  2   0.604592   4.801980       0.066892       0.000422      0.003497
  3  -2.614668  45.591565       0.068088       0.009034      0.003500
  4   0.815422   6.258168       0.068434       0.000196      0.003008
  ..       ...        ...            ...            ...           ...
  60  0.792715   6.123387       0.064522       0.000154      0.002924
  61  0.861496   1.975449       0.066161       0.000025      0.003350
  62  0.932183   0.821198       0.064766       0.000005      0.003334
  63 -1.853420  20.000004       0.066345       0.005553      0.002908
  64 -2.252078  21.201132       0.066926       0.014811      0.003258

  [65 rows x 10 columns],
           Training dataset     Testing dataset       mae       mse      rmse  \
  0   trained on window i-1  tested on window i  0.059322  0.006179  0.078609
  1   trained on window i-1  tested on window i  0.020186  0.000768  0.027713
  2   trained on window i-1  tested on window i  0.017560  0.000959  0.030966
  3   trained on window i-1  tested on window i  0.109771  0.030156  0.173655
  4   trained on window i-1  tested on window i  0.001797  0.000008  0.002852
  5   trained on window i-1  tested on window i  0.001257  0.000006  0.002378
  6   trained on window i-1  tested on window i  0.001386  0.000004  0.002121
  7   trained on window i-1  tested on window i  0.001925  0.000009  0.003068
  8   trained on window i-1  tested on window i  0.001046  0.000004  0.002092
  9   trained on window i-1  tested on window i  0.027308  0.001606  0.040081
  10  trained on window i-1  tested on window i  0.013958  0.000449  0.021198
  11  trained on window i-1  tested on window i  0.002153  0.000017  0.004082
  12  trained on window i-1  tested on window i  0.051001  0.003321  0.057625
  13  trained on window i-1  tested on window i  0.001814  0.000009  0.003040
  14  trained on window i-1  tested on window i  0.027413  0.001363  0.036922
  15  trained on window i-1  tested on window i  0.005500  0.000070  0.008344
  16  trained on window i-1  tested on window i  0.008218  0.000276  0.016613
  17  trained on window i-1  tested on window i  0.008258  0.000090  0.009464
  18  trained on window i-1  tested on window i  0.001689  0.000006  0.002368
  19  trained on window i-1  tested on window i  0.026021  0.001527  0.039072
  20  trained on window i-1  tested on window i  0.085233  0.017057  0.130604

            r2        mape  training_time  Testing Error  testing_time
  0   0.220600   32.784225       0.105830       0.006179      0.003245
  1   0.908789    5.242071       0.104885       0.000768      0.003748
  2   0.815216    3.415063       0.105150       0.000959      0.028831
  3   0.462294  266.482851       0.144470       0.030156      0.003619
  4   0.856940    7.786482       0.109313       0.000008      0.003480
  5   0.949367    9.188579       0.103276       0.000006      0.004323
  6   0.916534         inf       0.104479       0.000004      0.003601
  7   0.845420    6.260276       0.100426       0.000009      0.003890
  8   0.943812    3.012757       0.100277       0.000004      0.003663
  9  -0.423505   27.480311       0.100608       0.001606      0.003603
  10 -0.025834    7.855652       0.101011       0.000449      0.003130
  11  0.902176    1.135622       0.103132       0.000017      0.004031
  12 -2.879915   56.885526       0.103955       0.003321      0.003083
  13  0.986992    1.406111       0.102508       0.000009      0.004181
  14 -0.683444   12.887338       0.103810       0.001363      0.003203
  15  0.636335    2.145220       0.102520       0.000070      0.003733
  16  0.308361    4.405885       0.103487       0.000276      0.003343
  17  0.797052    3.695664       0.109054       0.000090      0.003905
  18  0.981426    0.705223       0.104194       0.000006      0.003617
  19 -0.290891   18.960536       0.107774       0.001527      0.004175
  20 -0.423285   20.652226       0.106793       0.017057      0.003554  ,
          Training dataset     Testing dataset       mae           mse  \
  0  trained on window i-1  tested on window i  0.003188  1.833094e-05
  1  trained on window i-1  tested on window i  0.123186  1.951874e-02
  2  trained on window i-1  tested on window i  0.004344  4.208997e-05
  3  trained on window i-1  tested on window i  0.000555  5.831648e-07
  4  trained on window i-1  tested on window i  0.089636  9.781455e-03
  5  trained on window i-1  tested on window i  0.001437  7.347604e-06
  6  trained on window i-1  tested on window i  0.013933  4.653791e-04
  7  trained on window i-1  tested on window i  0.001294  3.256318e-06
  8  trained on window i-1  tested on window i  0.004901  1.658477e-04

         rmse        r2        mape  training_time  Testing Error  testing_time
  0  0.004281  0.997969    0.827506       0.171364   1.833094e-05      0.004879
  1  0.139709  0.586228  398.121381       0.173938   1.951874e-02      0.004258
  2  0.006488  0.700441         inf       0.173942   4.208997e-05      0.004526
  3  0.000764  0.991030    1.858223       0.169924   5.831648e-07      0.004601
  4  0.098901 -4.568569   59.449576       0.170603   9.781455e-03      0.003430
  5  0.002711  0.995836    1.339648       0.170108   7.347604e-06      0.004707
  6  0.021573  0.756104    6.072349       0.172273   4.653791e-04      0.004449
  7  0.001805  0.994465    0.592718       0.169359   3.256318e-06      0.005420
  8  0.012878  0.882682    3.753602       0.175259   1.658477e-04      0.005544  ,
          Training dataset     Testing dataset       mae       mse      rmse  \
  0  trained on window i-1  tested on window i  0.044752  0.004162  0.064513
  1  trained on window i-1  tested on window i  0.003175  0.000029  0.005429
  2  trained on window i-1  tested on window i  0.045998  0.004706  0.068600
  3  trained on window i-1  tested on window i  0.001369  0.000007  0.002600
  4  trained on window i-1  tested on window i  0.015236  0.000490  0.022138
  5  trained on window i-1  tested on window i  0.001709  0.000022  0.004721

           r2        mape  training_time  Testing Error  testing_time
  0  0.917048  142.650213       0.241885       0.004162      0.005620
  1  0.771710         inf       0.242052       0.000029      0.005539
  2 -0.443568   33.023795       0.241158       0.004706      0.005157
  3  0.995636    1.007327       0.236198       0.000007      0.005577
  4  0.515591    6.209722       0.235375       0.000490      0.004583
  5  0.980273    1.195894       0.238350       0.000022      0.006461  ,
          Training dataset     Testing dataset       mae       mse      rmse  \
  0  trained on window i-1  tested on window i  0.087066  0.009079  0.095282
  1  trained on window i-1  tested on window i  0.029366  0.002714  0.052099
  2  trained on window i-1  tested on window i  0.003462  0.000076  0.008713
  3  trained on window i-1  tested on window i  0.003646  0.000029  0.005400

           r2       mape  training_time  Testing Error  testing_time
  0  0.729613        inf       0.424928       0.009079      0.004679
  1  0.146164  20.702443       0.328962       0.002714      0.006565
  2  0.959921   1.890334       0.317171       0.000076      0.006113
  3  0.939768   1.527755       0.313619       0.000029      0.005795  ,
          Training dataset     Testing dataset       mae       mse      rmse  \
  0  trained on window i-1  tested on window i  0.005517  0.000077  0.008749
  1  trained on window i-1  tested on window i  0.079683  0.008296  0.091081
  2  trained on window i-1  tested on window i  0.014650  0.000458  0.021390

           r2       mape  training_time  Testing Error  testing_time
  0  0.387738        inf       0.414206       0.000077      0.006544
  1 -2.966136  55.502004       0.416468       0.008296      0.004782
  2  0.423662   5.984024       0.392266       0.000458      0.005631  ,
          Training dataset     Testing dataset       mae       mse      rmse  \
  0  trained on window i-1  tested on window i  0.007509  0.000177  0.013319
  1  trained on window i-1  tested on window i  0.015332  0.000657  0.025633

           r2      mape  training_time  Testing Error  testing_time
  0  0.935084       inf       0.482826       0.000177      0.007319
  1  0.779331  6.880193       0.502988       0.000657      0.007272  ],
 900,
 6,
 900,
 6)